# Change these first
owner: clickdealer # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Click DMS
    url: https://myclickdealer.co.uk
  - name: Click Engage
    url: https://example.click-engage.co.uk
  - name: Click Media +
    url: https://api.myclickdealer.co.uk
  - name: Click Web
    url: https://www.clickmotors.co.uk

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://www.clickdealer.co.uk/wp-content/uploads/2020/02/ClickDealer_Logo_Colour.png
  name: ""
  introTitle: "Click Dealer Status Page"
  introMessage: ""
  navbar: []
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
